name: Validate data pack

on:
  pull_request:

jobs:
  Mecha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          stats: true
